spring.config.import=optional:file:../.env[.properties]

spring.application.name=ingestion-service

server.port=${INGESTION_SERVICE_PORT}
server.servlet.context-path=${SERVLET_CONTEXT_PATH}
spring.rest.ingestion-route=${INGESTION_ROUTE}

security.jwt.public-key=classpath:keys/public.pem

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

spring.data.redis.ttl.duaration=${INGESTION_REDIS_TTL_DURATION}

spring.rate.limit=${RATE_LIMIT}
spring.rate.limit.window.seconds=${RATE_LIMIT_WINDOW_SECONDS}

# Kafka Broker
spring.kafka.bootstrap-servers=${KAFKA_HOST}:${KAFKA_PORT}

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#Env
kafka.topic.raw-engagement-events=raw-engagement-events
